### ISSUE TITLE
Creating a new Gradle project in Eclipse results in a nested project /lib, and a build path error

### ISSUE THREAD

**Issue by Amr-Ibra** [eclipse/buildship#1077]
### Expected Behavior

1. Creating a new Gradle project in Eclipse should not result in a nested project /lib
2. The new project should use the system JRE 11, not 15

### Current Behavior

Creating a new Gradle project in Eclipse results in a nested project /lib, and a build path error.

### Context

Up-to-date Debian testing, Eclipse 2021-03 (4.19.0), Buildship 3.1.5.v20210113-0929

Only one default system JRE in Eclipse: java-11-openjdk-amd64.

Everything is at its default settings.

When I create a new Gradle project, I see two directories in the Package Explorer, one with the project name and another called lib, which is a nested project inside the project that I just created.

Plus, there is this build error:
![error-gradle](https://user-images.githubusercontent.com/45657128/113731058-bc4ab300-96f8-11eb-91b6-04c24a0a7b20.png)
even though the system JRE is 11.

### Steps to Reproduce 

Create a new Gradle project in Eclipse.

### Your Environment

Up-to-date Debian testing, Eclipse 2021-03 (4.19.0), Buildship 3.1.5.v20210113-0929

Only one default system JRE in Eclipse: java-11-openjdk-amd64.

Build scan:
https://gradle.com/s/f5sgatdtzco5q

**Comment by howlger** [comment]
This issue seems to occur only **when using Gradle 7.x**, which is the default in Buildship 3.1.5.v20210113-0929 that is included in Eclipse 2021-03 (4.19.0).

As **workaround** use **Gradle 6.x** or lower (see: https://stackoverflow.com/a/66857125/6505250)

(On Stack Overflow this issue has been already "reported" as question [here](https://stackoverflow.com/q/66005668/6505250) and [here](https://stackoverflow.com/q/66944673/6505250).)

**Comment by Amr-Ibra** [comment]
I made some testing. The last Gradle version that does **not** result in a nested /lib project is 6.6.1.
I set that as a specific Gradle version in Eclipse's preferences instead of the default Gradle wrapper.

**Comment by xtianus** [comment]
It happens in Windows too

**Comment by l3-g5** [comment]
Is someone working on this issue? This issue has been discussed in the Eclipse IDE working group (see https://www.eclipse.org/lists/eclipse-ide-wg/msg00037.html) since it might be a severe issues for new gradle users in Eclipse. Any idea what needs to be done, here?

**Comment by antiflash1** [comment]
Another workaround. If you still want to use latest Gradle version. After Eclipse create the new project with nested lib sub project, Edit the "settings.gradle file to delete "include('lib')" line. Then delete the project and subproject from eclipse (without deleting its contents). Close eclipse. Manually move contents from nested lib folder  to root project folder. Delete lib folder. Open Eclipse and import the Existing Gradle Project

**Comment by N3TC0D3** [comment]
> Another workaround. If you still want to use latest Gradle version. After Eclipse create the new project with nested lib sub project, Edit the "settings.gradle file to delete "include('lib')" line. Then delete the project and subproject from eclipse (without deleting its contents). Close eclipse. Manually move contents from nested lib folder to root project folder. Delete lib folder. Open Eclipse and import the Existing Gradle Project

Bro after a long time i decided to retry gradle and this pissed me off so much i almost got rig of it again and you literally saved my day. Thank you!

**Comment by donat** [comment]
@Amr-Ibra You reported two issues at once:
- unbound Java classpath container on new Gradle projects
- unwanted `lib` subproject generated by `new Gradle project wizard`

I did some initial testing. I fired up a new Ubuntu instance, installed java11 + Eclipse for Java Developers, launched Eclipse, and created a new Gradle project. I was not able to reproduce the `Unbound classpath` issue. For me, Java 11 was correctly picked up on the classpath.

To highlight what could be the root cause, let me add a bit of context on how the project creation works. Buildship uses the Java runtime from its configuration to call `gradle init`. If nothing is specified, then it falls back to the Java installation that hosts the curent Eclipse instance. The generated project doesn't have any configuration with regards to the Java runtime (targetCompatibility, toolchains) so Buildship will try to use the same Java runtime to setup its classpath. 

I assume you either run Eclipse with Java 15 or you have in the creation (or workspace) configuration. I'm happy take another look if you provide precise reproducer steps.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/419883/141822877-86cb2530-c2b4-42d3-a469-0acce79f39ae.png">

Regarding the separate `lib` project, it became a default structure in `gradle init`. I think we can remove the separation with an additional task argument. We can add it to the project creation wizard UI if you think it is useful.

**Comment by xtianus** [comment]
Can anyone link to some docs about the separate lib project, why it's there and how it is supposed to be used?
The option to keep the old structure would help a lot.

> Regarding the separate lib project, it became a default structure in gradle init. I think we can remove the separation with an additional task argument. We can add it to the project creation wizard UI if you think it is useful.

**Comment by donat** [comment]
> I think we can remove the separation with an additional task argument.

I was wrong. The `--split-project` argument in the init task configures something else. Right now, there's no easy way to get rid of the `lib` subproject.

**Comment by donat** [comment]
The `lib` subproject reflects what is called "idiomatic" project structuring:
- the root directory contain the files associated for the whole build (wrapper, gradle.properties, settings file, etc)
- the subproject contains the sources and the build script specific for the `lib` module.

It might seem weird to have this separation on this scale, but gives a clearer indication on how to evolve the project further. 

(FYI there's an interesting (advanced) chapter in the Gradle reference documentation about how structure large projects: https://docs.gradle.org/current/userguide/structuring_software_products.html)

**Comment by Amr-Ibra** [comment]
> I'm still waiting for a stable reproducer for the unbound java classpath container issue.

Sorry for the very late reply. I was away from my laptop for several weeks.

Steps to reproduce on Debian / Ubuntu:

0. Install the default JDK-11 (`sudo apt install default-jdk`)
1. Download Eclipse as a package **without** the bundled JRE from [here](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2021-09/R/eclipse-java-2021-09-R-linux-gtk-x86_64.tar.gz), do not download the installer
2. Run Eclipse from the extracted archive, it will use the system JRE-11
3. Install the Buildship plugin
4. Create a new Gradle project

The error is there:
![image](https://user-images.githubusercontent.com/45657128/144315161-29123d1d-d98d-4442-bb91-7b054c588cab.png)

**Comment by donat** [comment]
@Amr-Ibra I followed your instructions in a new Ubuntu virtual machine. For me, everything works as expected: the new project is created successfully and the `JavaSE-11` JRE system library is being picked up for the project. Are you sure your Eclipse instance is running with Java 11? You can check it the `Help > About Eclipse IDE` menu item.

**Comment by Amr-Ibra** [comment]
OK, I made a screen recording on the issue. Make sure you leave all settings as default.

https://user-images.githubusercontent.com/45657128/144668467-6a7b956e-8cc2-4b53-ae05-de0b9e4ed2e9.mp4

**Comment by donat** [comment]
Thanks for the recording! Can you create yet another screenshot from the Eclipse runtime configuration? 
In the menu, select `Help > About Eclipse IDE`, then in the dialog click the `Installation Details`  button then navigate to the `Configuration` tab. What entry do you have after the `-vm` flag?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/419883/144816829-0d6ccf94-853c-4d6b-8c66-b1ee216c94d8.png">

(Most probably it's going to be Java 15, because that's what Buildship picks as a default JDK.)

**Comment by Amr-Ibra** [comment]
Thanks for pointing me in the right direction. I actually deleted my old Eclipse installation and reinstalled it using the installer this time to see how it goes.

> (Most probably it's going to be Java 15, because that's what Buildship picks as a default JDK.)

Yes, in the old installation it was Java 15 for some unknown reason, although I only have Java 11 installed. (Maybe because Eclipse was downloaded as a package and not through the installer.)

After the new installation, it shows Java 11.

![eclipse_inst_conf](https://user-images.githubusercontent.com/45657128/144889933-c6d2e79d-1c21-44c7-a8f4-00f3975f001d.png)

And I don't see the build path error any more. A new Gradle project picks the system JRE-11 as normal. So I guess there isn't an issue here after all.

Thanks a lot.

**Comment by donat** [comment]
I'm glad you found the solution.

**Comment by Cozymike** [comment]
> Another workaround. If you still want to use latest Gradle version. After Eclipse create the new project with nested lib sub project, Edit the "settings.gradle file to delete "include('lib')" line. Then delete the project and subproject from eclipse (without deleting its contents). Close eclipse. Manually move contents from nested lib folder to root project folder. Delete lib folder. Open Eclipse and import the Existing Gradle Project

Tried this but now I'm getting this error

`"org.eclipse.buildship.core.internal.UnsupportedConfigurationException: Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace line 0 Gradle Problem"
`

**Comment by xtianus** [comment]
The error is saying that your project and your workspace share the same folder, which is wrong. The project should be a subfolder of the workspace. Your error is confusing because you created a project named "Java & Kotlin Workspace" but in Eclipse the "workspace" is a container for "projects".
I suggest that you don't use the "&" character nor spaces nor "workspace" in the java project name or in the parent path to have a more readable error message. 

> Tried this but now I'm getting this error
> 
> `"org.eclipse.buildship.core.internal.UnsupportedConfigurationException: Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace line 0 Gradle Problem" `

**Comment by Cozymike** [comment]
> The error is saying that your project and your workspace share the same folder, which is wrong. The project should be a subfolder of the workspace. Your error is confusing because you created a project named "Java & Kotlin Workspace" but in Eclipse the "workspace" is a container for "projects".
> I suggest that you don't use the "&" character nor spaces nor "workspace" in the java project name or in the parent path to have a more readable error message. 
> 
> > Tried this but now I'm getting this error
> > 
> > `"org.eclipse.buildship.core.internal.UnsupportedConfigurationException: Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace Project Java & Kotlin Workspace location matches workspace root E:\Creative Software\Eclipse IDE Java & Kotlin\Java & Kotlin Workspace line 0 Gradle Problem" `
> 
> 

The "Java & Kotlin Workspace" is the name I gave to the workspace folder, I have separate workspaces for each eclipse install

**Comment by eduhsoto** [comment]
> Another workaround. If you still want to use latest Gradle version. After Eclipse create the new project with nested lib sub project, Edit the "settings.gradle file to delete "include('lib')" line. Then delete the project and subproject from eclipse (without deleting its contents). Close eclipse. Manually move contents from nested lib folder to root project folder. Delete lib folder. Open Eclipse and import the Existing Gradle Project

Currently in Eclipse IDE for Enterprise Java and Web Developers 2026-03 (4.39.0) , the IDE stills creates  the nested /lib, so I had to follow  this workaround as well.
