### ISSUE TITLE
Support debugging tests

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#249]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Thursday May 19, 2016 at 09:02 GMT_

----

## Motivation

Quite often a test surfaces a problem that the user wants to debug. Buildship should offer a "Debug as Gradle test" option, which automatically attaches a debugger to the test running inside Gradle.
## Proposed Change

TBD
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
Bugzilla issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=471730

**Comment by staffanf** [comment]
@oehme I noticed that this issue does contain the complete feature request from the bugzilla issue linked by @donat . This issue description does not cover JavaExec debugging which for me is more interesting than debugging unit tests.
Either this issue should be expanded to cover JavaExec's or a another issue should be created. Which one do you prefer?
Also I'd like to push for looking at this since it is the currently most upvoted issue.

**Comment by donat** [comment]
Hi @staffanf!  So I would just create a new issue GitHub issue with the explanation of the desired behavior and with a reference to this issue.

It would be awesome if the users could execute Gradle builds in debug mode within Eclipse. It's certainly a complex story to implement, so let us know if you need any help, we are happy to support your effort. 

I think there are two ways to go. You could either
- start with a specification in a new GH issue and where we can discuss how the final state should look like, or
- create a prototype version which we could give feedback on how to proceed.

**Comment by staffanf** [comment]
@donat Although I noticed this discrepancy I will not be contributing to this issue except for contributing use-cases/feedback/snapshot-testing.
Like many other, we are a mixed shop with some preferring Eclipse and others IntelliJ. I'm in group #2 but I'm also the one responsible for converting our builds to gradle so we would like features parity.
For me, not being able to debug JavaExec tasks is currently the biggest omission for Buildship compared to IntelliJs support.
For us, this currently this involves generating xml launch configurations from JavaExec's. This is kinda fragile since the xml specification is not a official eclipse spec and can be changed.

So I could create a new issue, but my guess is that those that have +1 this post are more interested in debugging JavaExec's than just tests since this issue was created from the bugzilla issue that specifically mentioned debugging tomcatRun.
But looking at the original bugzilla issue, @oehme was actually the only one mentioning either tests/JavaExec.

Maybe we there should be 3 separate issues depending on how different the implementation is?

1. Debugging JavaExec's
2. Debugging Test tasks (this current issue)
3. Debugging any task, ie. debugging gradle logic

I would guess that people would want them in that order, although I could be wrong.

**Comment by donat** [comment]
Sorry for the late reply. It's hard to tell what exactly the commenters and +1'ers want, but I'm willing to guess is that the biggest missing feature is the lack of Gradle option in the `Debug as...` menu. But how exactly this feature should look like? I can imagine a couple of implementations (extending the Gradle editor, hooking into the Tasks view, etc) so we'll need an actual spec where we could discuss how this feature should look like. I'd say please go ahead and open a new ticket and elaborate on step no. 1.

**Comment by walec51** [comment]
Just take a look how Netbeans and IntelliJ Gradle integration looks like.
You can right click on a Gradle task in the tasks view and choose to run it in debug mode.
You can select any test method of class and choose to run it in debug mode which runs it using Gradle and NOT the IDEs internal test runner. In Intellij this requires an extra configuration step. On Netbeans works with through gradle out of the box.

**Comment by donat** [comment]
I've merged the PR containing test debugging. There are a couple of enhancements I want to do, but this will enable clients to evaluate the feature using the latest snapshot.

**Comment by donat** [comment]
The latest snapshot now contains the changes. If you are interested you can go ahead and try it out. Any give us feedback, please :)

**Comment by ams-tschoening** [comment]
This is what one needs to do:

https://discuss.gradle.org/t/buildship-3-1-2-is-now-available/33034
