### ISSUE TITLE
Run tasks on synchronization

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#265]
## Motivation

Some projects have setup tasks that need to be run before they can be used in the IDE. That might be a long-running code generator or some configuration task for an Eclipse plugin that Buildship has no model for.

This would be an inexpensive workaround for our missing WTP support. Instead of creating a full-blown tooling model for WTP, we could just run the `wtpComponent` and `wtpFacets` tasks.
## Proposed Change

Add `eclipse.synchronizationTasks` to the Gradle Eclipse API, expose them via the TAPI and run them before the actual project synchronization.

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Monday Aug 29, 2016 at 09:02 GMT_

----

The WTP case can be implemented even simpler by hardcoding support as in #85 .

**Comment by donat** [comment]
Related issue in Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510331

**Comment by adammurdoch** [comment]
It would be nice if we solved this by offering a way to declare the developer _inputs_ in a Gradle build definition, and simply make sure these things are built on import and then kept up-to-date as things change. This way, the inputs can be made usable regardless of which IDE the developer is using.

We might model these as 'buildable things' somewhere that you declare, or we might infer that generated source files or resources that are inputs into the main or test source sets should be built prior to use from the IDE.

**Comment by oehme** [comment]
@adammurdoch this ticket is more about Eclipse-specific things that need to be generated when you "sync" the Eclipse configuration. This is really just a convenience for Gradle plugins that don't want to build a full-blown tooling model + Eclipse plugin, but just want to create some configuration file.

There is another ticket (#266) for what you are referring to: Tasks that need to be run in order to keep generated sources up-to-date. These should be IDE independent, but I don't think we're there yet: We want to replace the built-in generators/compilers in IDEs, but that requires us to provide the same rich diagnostics that IDEs currently provide (e.g. collecting all errors and warnings from all generators/compilers and putting them on the correct source files). Of course doing exactly that could be the solution for #266 instead of having an Eclipse-specific list of tasks.

**Comment by Kameecoding** [comment]
what's the status of this feature is it being worked on?

**Comment by ChristianCiach** [comment]
We need this to automatically trigger `eclipseFactorypath` and `eclipstJdtApt` of the APT-Plugin. There is no way that I convince all my colleagues to manually run these tasks every time the factory path changes.

**Comment by Gentleman1983** [comment]
Same here considering the `eclipse` and `eclipse-wtp` tasks.

**Comment by ybayk** [comment]
This feature indeed would be very useful for generated sources. Currently we have to instruct developers that Gradle import/refresh is not sufficient, and one extra task has to be executed from command line.

**Comment by stefanleh** [comment]
Same here. We got a very prehistoric way of copying libs from a central webshare to the lib folder of the project for updating dependencies when in a sealed environment (no Nexus in network / no Internet at all). This should be triggered via Gradle task when "Gradle refresh project" is run.

**Comment by ChristianCiach** [comment]
Sad to see that this feature didn't make it for Buildship 3.0. Unfortunately, Buildship is unusable for our company as long as the workspace is in a broken space after synchronization before additional tasks are run. Why no love for annotation processors?

**Comment by donat** [comment]
@ChristianCiach We didn't implement this for Buildship 3.0 as the release already contained way too many changes. The feature list might not seem too long but internally we did major refactorings. 

FYI we have a rough plan what comes next. In 3.1 we're going to fix #829, then we'll implement this issue.

**Comment by donat** [comment]
The [Gradle-side implementation](https://github.com/gradle/gradle/pull/8823) for this story is ready. I'll merge it next week.

**Comment by lukeu** [comment]
Great stuff! If I wanted to take this for an early spin: will I need to build buildship from source, or is there an update-site URL I can use?

Regarding how `eclipse.synchronizationTasks` works: so I should simply list names of gradle task(s)?

  eclipse.synchronizationTasks = [ 'generateWhatEclipseDoesnt' ]

#266 talks about performing actions upon build, but I don't see a different trigger for that? For example, we also have a little task to encrypt a resource file, which can be edited quite frequently when working in that area. It would be great if that could just happen on a build (Ctrl+B, or Right->click the specific eclipse Project, Build) which usually takes a split-second, rather than [Gradle -> Refresh] which can take 30s or so even for a no-change refresh.

**Comment by donat** [comment]
> will I need to build buildship from source, or is there an update-site URL I can use?

No, you'll only need the latest snapshot and Gradle 5.4-rc-1. We have some difficulties ATM as the Eclipse servers disabled our account, but once that's fixed I'll kick of a snapshot build. I'll let you know here when you can proceed.

> Regarding how eclipse.synchronizationTasks works: so I should simply list names of gradle task(s)?

Yes, that should work.

> It would be great if that could just happen on a build 

That's precisely how the `eclispe.autoBuildTasks` work.

**Comment by lukeu** [comment]
> That's precisely how the `eclispe.autoBuildTasks` works.

Super! I saw that mentioned in earlier discussions but didn't realise it was also done.

**Comment by donat** [comment]
The snapshot release is out, you can give it a go.

**Comment by donat** [comment]
A quick heads-up. We scheduled the release review to 1st May, and the release will follow shortly. Early adopters can evaluate the new feature with the [latest snapshot or milestone](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md).

**Comment by ChristianCiach** [comment]
Just to avoid confusion: `eclipse.synchronizationTasks = [ 'generateWhatEclipseDoesnt' ]` is not the correct syntax. `synchronizationTasks` is not a property.

Following the [api documentation](https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/eclipse/model/EclipseModel.html), this should work:

```
eclipse.synchronizationTasks eclipseFactorypath, eclipseJdtApt, eclipseJdt
```

**Comment by lukeu** [comment]
> Early adopters can evaluate the new feature with the latest snapshot or milestone.

Thanks! Here's my feedback:

`synchronizationTasks` so far is working very nicely :-)

With `autoBuildTasks` I encountered two issues:
   1. It only seems to do anything while [Project > Build Automatically] is enabled. I see that is explicit in the naming... :-) However I do not think it is useful for this feature to distinguish between the types of action that initiated a project-build, rather it should execute consistently whenever a project is built regardless of the action that triggered that.
  2. My intended use-case involves post-processing some resource files, and the result ends up being out-of-date. Specifically if I...
   * edit the original resource,
   * save (to *auto* build it)
   * wait (for any auto-refresh resources to complete) 
   * launch my application

Then I see the result corresponding to the build one prior. Now it is probably the case that I need to rework the (re)source directory structure or something to fix this. However I didn't play with it too much since (1.) is already a blocker. And as a workaround I can just put this in `synchronizationTasks`, which seems to build robustly without other build-script changes.

**Suggestion:** Could the documentation say a bit more about at which point the `autoBuildTasks` step will occur in the sequence of operations that Eclipse performs? The wording "during the Eclipse auto-build" is rather vague.

**Comment by donat** [comment]
@lukeu I think the auto-builder task is correct regarding it only triggers when the `Project > Build Automatically` is enabled. I wouldn't want to see expensive calculations in my IDE if I explicitly disabled that. I can still see it happening, just in a different hook (i.e a separate `eclipse.resourceChangeTasks`).

**Comment by ChristianCiach** [comment]
Just an idea: Eclipse has the concept of "Save actions" (you can search the preferences for this). I think it would be great to be able to trigger Gradle tasks that could be explicitly configured as save actions.

**Comment by lukeu** [comment]
Hi @donat,
>  I think the auto-builder task is correct regarding it only triggers when the Project > Build Automatically is enabled.  I wouldn't want to see expensive calculations in my IDE if I explicitly disabled that.

Well maybe that is based on a particular mode of operation? Eclipse has a range of preferences - for example "auto-save upon (presumably a manual) build" sounds like the opposite way around to Tools > build automatically. (Not that I use that myself)

I don't like expensive operations running repeatedly in the _background_, and prefer to be in control over them. So I do these 3 steps manually: (1) refresh Gradle, (2) Ctrl+(Shift+)S to save all, (3) Ctrl+B to build. Importantly, the last one swaps the updated code into a running debug session, so I definitely want to be in control of that. I can avoid applying changes I know would break what I'm testing. (But maybe I want to save & commit to git anyway.)

So this seems to be leading to wanting potentially 3 save/build triggers:
 1. Run tasks with auto-builds
 2. Run tasks on manual-build
 3. Run tasks when resource is saved (which I infer is what `eclipse.resourceChangeTasks` was suggesting?)

But personally I see as a mistake to split 1 and 2. Why would we want an explicit build command (Ctrl+B) to only do a partial build? Where the only way to get the code into the completely-built state is to turn Auto Build on (and then off again)? I don't think the design should let the user get into that confusing "partially-built" state at all. 

Anyway, there be ways to avoid "expensive calculations" upon build though, right?
 * don't run the expensive tasks then (maybe move them to do during a sync?)
 * keep using auto-build
