### ISSUE TITLE
Run tasks when Eclipse build is triggered

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#266]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Thursday May 19, 2016 at 15:21 GMT_

----

## Motivation

People often have little code generators in their build for which there is no Eclipse support. But thanks to Gradle's performance, running tasks on every Eclipse auto-build is feasible.
## Proposed Change

Add `eclipse.autoBuildTasks`, expose them via the TAPI and let the Buildship builder run them on every auto-build of the project.
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by oehme** [comment]
Yes, the term auto-build is a little misleading here: It would work whenever the builder is triggered, both manually and automatically.

**Comment by lukeu** [comment]
I thought I'd mention a use-case that might be relevant. Currently getting Eclipse to compile is a 3-step process for us, as we generate source files outside of the project directory.

 1. `gradle generateSources`
 2. Right-click Project  >  Gradle  >  Refresh Gradle Project 
 3. Build (Ctrl+B)

Step 2 is required because if the externally-generated folders don't exist, Buildship will not have constructed (or updated) linked-resources into the Eclipse projects to use as source folders.

Do you envisage it being possible (or desirable) to automate step 2 via the `eclipse.autoBuildTasks` proposal?

**Comment by oehme** [comment]
Yes, that's covered by #265

**Comment by lukeu** [comment]
Great thanks. Right so maybe `eclipse.synchronizationTasks` could just construct the gen-src dir, ensuring it exists prior to project-sync; then `eclipse.autoBuildTasks` for the code-gen? I can imagine that would work nicely.

**Comment by ericnondahl** [comment]
@lukeu We have a similar use case, and committed the empty generated source folders that can be added to the eclipse project model so that the full `Refresh Gradle Project` is not needed - just an eclipse refresh to pull in the new sources. Just throwing that out there in case it is helpful in the short term before builder support is added to buildship - removes having to do a repeated Gradle project import after the sources are generated.

**Comment by lukeu** [comment]
@ericnondahl Thanks for the tip. In our case it's to a non-repo directory (and in my specific case, a different drive. This fits in with our GNU-make parts of the build, and I gather is useful in our CI setup.) Still, the generated-source folders don't change often so the 3 steps would be done fairly infrequently & is no biggie for me now that I've figured out what's going on. (I'm getting good at it - I toggle my 30-module workspace between Maven and Buildship about once daily while we're transitioning!) My interest here is more in seeing Buildship grow even slicker - ideally zero configuration (for other team members who don't want to dive deep into Gradle, and when the build structure changes in the future.)

**Comment by eximius313** [comment]
Are there any plans to implement this enhancement?

**Comment by donat** [comment]
@eximius313 Yes, we still want to implement this. Currently, we have other priorities (like #354), but we'll consider this feature in our next planning meeting.

**Comment by ChristianCiach** [comment]
We need this to automatically trigger `eclipseFactorypath` and `eclipstJdtApt` of the APT-Plugin. There is no way that I convince all my colleagues to manually run these tasks every time the factory path changes.

**Comment by Gentleman1983** [comment]
Same here considering the `eclipse` and `eclipse-wtp` tasks.

**Comment by Frontrider** [comment]
It's a requirement for us right now.

**Comment by donat** [comment]
Also implemented as part of #871.
