### ISSUE TITLE
Only offer "Run as Gradle Test" on test classes

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#348]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=486170

**Comment by kevinmilner** [comment]
I second this request. A workaround I would be happy with is to add a configuration option to just disable the "Gradle Test" launcher altogether, as I never use it and it serves as an annoyance.

**Comment by gte811i** [comment]
Very annoying, I third this request.  It seems simple enough to have the Gradle launcher conflict with the Java launcher and then in Run/Debug->Launching->Default Launchers one could set the default behavior to either the Gradle launcher or the regular Java launcher.  Please fix.

**Comment by donat** [comment]
I think this can be fixed relatively easily. Buildship should show the `Run as Gradle Test` if the fully qualified name of the target class matches a specific pattern (`**/*Test`). Then there should be a workspace preference to configure that pattern. @oehme WDYT?

**Comment by oehme** [comment]
> Buildship should show the Run as Gradle Test if the fully qualified name of the target class matches a specific pattern (**/*Test). Then there should be a workspace preference to configure that pattern.

That would be duplicating things that Gradle already knows (i.e. the test framework can tell us what is a test class and what isn't). As a user I wouldn't want to repeat myself. I'd rather go with one of two alternatives:

a) Ask the JUnit/TestNG Eclipse plugins whether the class contains a test
b) Ask Gradle what classes contain tests

**Comment by oehme** [comment]
As a first simple step, how about only offering it on things in source folders whose relative path contains the word "test"?

**Comment by donat** [comment]
> As a first simple step, how about only offering it on things in source folders whose relative path contains the word "test"?

This is almost a one-liner as the `TestLaunchShortcutValidator` already has a reference to the selected `IJavaElement` instances. Given the current project priorities, I think we should go with this.

Nonetheless, matching project-relative paths to a pattern doesn't complicate things and it would help enterprise deployments to configure Eclipse to their liking. Even without a UI, I'd do this.

**Comment by gte811i** [comment]
Just to clarify the issue that I'm have.  Without Gradle, I create a Java project with multiple class files.  I have one main class file.  When I initially tell eclipse to run that project it will search for a main class file and then when I go to the other class files and hit CTRL+R (or the equivalent) eclipse will automatically run the main file because I have selected "Launch the Selected resource or active editor. If not launchable . . .launch the associated project".


With buildship installed when I do this same process, but I get a pop-up window that says "Select a configuration to launch": and then all the Gradle commands for the project are listed.  This pop-up screen may be the "Run as Gradle Test:" window but it just says launch configurations.


With buildship, there is no way (that I see) to enable the generic Eclipse functionality of change some code, and without switching to the main file automatically run the associated java project for that file.


I would imagine checking the "Gradle Project" in the Launch Configurations filter, i.e. "Filter checked launch configurations" would disable this launch window; it does except it then automatically runs the normal gradle build instead of disabling Gradle launching entirely.


I think a clean solution would be to add the Gradle Launcher in the Default Launchers section of Launchers and then a user could select which launcher is the preferred launcher when there are multiple launchers (i.e. Eclipse and Gradle).


________________________________

**Comment by oehme** [comment]
@gte811i Thanks for clarifying. Forcing a launcher decision from the user might become interesting when we allow running main classes with Gradle at some point. Right now we only allow tests and your main class just shouldn't have the "Run as Gradle Test" option at all.

**Comment by gte811i** [comment]
You are welcome, thank you for allowing me in the conversation!  I think I understand better, that the default behavior of Gradle buildship should be to only run Gradle Test so I shouldn't even have a gradle launching option in normal Java classes and it should never run from them.  Very good.  

I appreciate you working on this.  It's been a minor annoyance since I integrated gradle (prior to buildship) a couple of years ago.  I developed a solution of modifying several config files inside of one of the gradle plug-ing jars, repackaging and running. It worked . . . until there was an update.

**Comment by netmikey** [comment]
Part of the OP's suggestion was this:

> In the meantime then, could there be a user-preference disable this action globally? In my workflows, I only want to use the JUnit launcher to test a given class/project, and would be more than happy to run Gradle from the command-line or other Gradle view when I want to use Gradle to run the tests.

I'm exactly in the same situation, same workflow.

Plus, I *never* ran a "Gradle Test", yet when I'm working on a JUnit test in Eclipse and hit `Ctrl+F11` it almost always executes "Run as Gradle Test". I can't insist enough how annoying this is...

Really, *please* let us disable that run action altogether.

**Comment by kevinmilner** [comment]
A fix for this seem so simple, and would remove so much annoyance. Is anyone out there? @donat?

**Comment by donat** [comment]
@kevinmilner A relatively simple solution would be to contribute the `Run As > Gradle Test` entry only if the class is part of the test source sets.

**Comment by donat** [comment]
@kevinmilner The fix is in the latest snapshot. You can install it from the 3.x snapshot update site: http://download.eclipse.org/buildship/updates/e47/snapshots/3.x.

**Comment by donat** [comment]
@kevinmilner My pleasure. The 3.x stream should be pretty stable, but if you experience any problems please let us know.

**Comment by donat** [comment]
@gte811i Can you be more specific? I had a quick check, and for me, the `Run as Gradle Test` action doesn't appear for non-test classes in Buildship 3.0.

**Comment by donat** [comment]
@gte811i Can you copy-paste the project's `.classpath` file? Also, which source folder contains the `MainModel` class?

**Comment by gte811i** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/test" path="src">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="resources">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
------------------------------------
src/com/xxxx/yyy/model/MainModel.java

Now I do have some test files in
src/com/xxxx/yyy/test/*.java.
Is it keying off of the test folder being in the same superfolder?  
(and thank you for looking into this).

**Comment by gte811i** [comment]
Fixed it.  In my .gradle file I had a
test {
  java srcDir 'xxxx'
}
It was keying off that srcDir, which included the MainModel.java file. I changed that and it worked.

**Comment by donat** [comment]
Glad you found the solution. I was going to propose a similar approach.
