### ISSUE TITLE
Provide smart import support

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#356]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=469636

**Comment by armandomejiam** [comment]
+1

**Comment by donat** [comment]
A few tips on how to implement smart import support is provided by @mickaelistria at #751.

**Comment by donat** [comment]
Another request for smart import in Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=549760

**Comment by thokuest** [comment]
Yet another request for smart import in Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559074

**Comment by maxandersen** [comment]
I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=559074 as https://projects.eclipse.org/projects/tools.buildship/developer points to bugzilla :)

But since then I found this issue is open for smart import for gradle.

I've read through the various comments I honestly don't follow what the remaining blockers are for providing a basic 'if build.gradle file available, mark it as a gradle project and trigger import" feature ?  vscode-java support does auto-import and it seem to work quite well (maybe @fbricon can comment on how they did it).

it is literally the one thing that makes eclipse gradle experience stand out from from vscode and intellij that with both of those plain eclipse, maven and gradle projects "just opens" but for eclipse it is everything but Gradle that is handled.

Would be great to see if we could get this enabled for gradle - willing to submit patches/test it out if can get an update on what are the knowns blocker if any.

**Comment by donat** [comment]
@maxandersen 

> projects.eclipse.org/projects/tools.buildship/developer points to bugzilla :)

Unfortunately, there's no way to configure the bug tracker on the project page. 

> I've read through the various comments I honestly don't follow what the remaining blockers are for providing a basic 'if build.gradle file available, mark it as a gradle project and trigger import. 

I think there should not be any blockers to implement this feature, at least not big ones. We simply had bigger issues/missing features at our hands to work on. 

> Would be great to see if we could get this enabled for gradle - willing to submit patches/test it out if can get an update on what are the knowns blocker if any.

Awesome, thanks for volunteering. Well, for started I'd recommend reading through the [initial conversation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469636) on the topic why we didn't implement this feature right away. I think the problems are still valid now: the importer works per project folder whereas Gradle can import one build (containing multiple projects) at a time.

If you have an idea how to implement this feature then I'd suggest you to just create a rough prototype implementation. It doesn't have to be perfect or even pretty, just demonstrate the proposed solution. I'll be more than happy to review it and guide you forward. With regards to the IDE setup, you'll find instructions [here](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md).

If you are stuck with anything let me know. I'm happy to give guidance.

**Comment by mickaelistria** [comment]
>
> Unfortunately, there's no way to configure the bug tracker on the project
> page.
>
You can send a mail to webmaster@eclipse-foundation.org for that, you can
even ask for removal of your Bugzilla component if you wish to use GitHub
exclusively (some projects I work with have done that)

**Comment by maxandersen** [comment]
> Awesome, thanks for volunteering. Well, for started I'd recommend reading through the [initial conversation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469636) on the topic why we didn't implement this feature right away. I think the problems are still valid now: the importer works per project folder whereas Gradle can import one build (containing multiple projects) at a time.

Yeah, so I'm trying to grok why gradle import is any different than maven here ? it should/would have the same issue here I reckon ?

**Comment by donat** [comment]
@mickaelistria I didn't know that's a possibility. I'll contact the webmaster soon.

@maxandersen Correct. I don't know about Maven, but it's highly likely that they have the same problem.

**Comment by mickaelistria** [comment]
>  I don't know about Maven, but it's highly likely that they have the same problem.

Which in practice was never reported as a problem by users ;) So it could be that this problem doesn't often exist in real life.
That said, I think the `ProjectConfigurator.findConfigurableLocations()` doesn't prevent from importing files from another branch.

**Comment by laeubi** [comment]
Is there any progress on this? I'm asking because this was complained about at [EclipseCon 2022](https://www.eclipsecon.org/2022/sessions/what-eclipse-ide-must-learn-other-ides-survive) that we have [bad user experience with m2e](https://github.com/eclipse-m2e/m2e-core/issues/1012) when [importing junit5 project](https://github.com/junit-team/junit5), but the real problem is/was that junit5 is actually a gradle project but don't support the smart-import.

I have read through the linked tickets and beside they are quite old I think the very minimal step would be to simply if the user selects a "project root" it is reported as a (single) gradel project, then when this project is imported it can do all the efficient things and detect sub projects and so on I get when I choose "import existing gradle project".

So to bring this forward I can offer:
- help with initial implementation proposal
- improving the platform-API if required

I'm just not familiar enough with gradle itself, so would need assistance (and probably improvement of initial contribution) by buildship committers.

FYI @vogella

**Comment by laeubi** [comment]
I have now created a PR here:
- https://github.com/eclipse/buildship/pull/1219

any help / feedback would be appreciated.

**Comment by vogella** [comment]
Thanks @laeubi
