### ISSUE TITLE
Duplicates in task view

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#360]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510388

**Comment by mustafau** [comment]
This happens when a project is included in more then one composite build. 

<img width="1505" alt="screen shot 2017-05-27 at 10 08 35" src="https://cloud.githubusercontent.com/assets/881222/26519076/a495aa8a-42c4-11e7-8c24-2f968c59615c.png">

**Comment by kcclaas** [comment]
I have a flat project structure, with some projects acting as subprojects of multiple other projects. In the tasks pane, this shows up as the subproject existing twice, with one version that has runnable tasks, and the others don't. I have an example repo for this setup [here](https://github.com/kcclaas/buildship_multiproject_bug_sample)

It appears which version of the project in the tasks pane is the runnable one is dependent on which project it considers to be its root. When I refresh the gradle build for a project other than root, and then refresh the tasks pane, the runnable copy switches. If I import a new gradle project that depends on the subproject, the new one is now the root.

From a command line, I can go to any of these subprojects, and run the build as though it was the root. It seems weird that I can't do something so simple within eclipse. Separating the projects into multiple worksets/workspaces doesn't work, and I haven't found a reasonable work around. 

Would it be reasonable to have an option to consider each project its own root as far as the tasks pane is concerned (and only include it once)? This would hopefully allow there to be only one copy of each project in tasks, and make its tasks runnable regardless of how many other projects depend on it.

**Comment by oehme** [comment]
> with some projects acting as subprojects of multiple other projects.

This is not something that we support and not an intended use of Gradle. It's hard to detect, which is why we don't fail automatically for this case. It will completely mess with your incremental build performance. What's the use case for this? Depending on the use case you are probably much better off with either 

1) making all projects part of one multi-project build or
2) using binary dependencies and using composite builds when you actually do need to co-develop them

> This happens when a project is included in more then one composite build.

In the IDE, every build can only be included in *one* other build at any given time. Depending on which build a project is included in, it's configuration can (and often will) be different. We should add some validation for this.

**Comment by kcclaas** [comment]
Our project structure is a bit of a mess. We were building everything purely through eclipse, with some people being able to build a given project while others couldn't (without a bunch of work to figure out what they were missing). I started moving everything to gradle over a year ago, before composite builds were introduced, so I'm not terribly familiar with what they can do.

Among our dozens of projects we have:
Base libraries depended on by other projects
Other libraries that depend on those
Front-end webapps that depend on both types of library
One project that is both a library for others, and a deployable front-end webapp
Android projects that also depend on the base libraries

None of these projects are published anywhere. I currently have each project set up such that it could be run as the root build if desired. I understand that it's not the intended structure/use, but it's what I've been able to do that actually works. If I could do these as composite builds (which I'm not sure I can, due to libraries depending on each other), "co-development" would be the default, as many of our front-end changes require changes in the library projects. I would have to think about the possibility of a single multi-project build including so many inter-dependent projects. 

I'm currently just trying to make all of this work in eclipse for my colleagues as seamlessly as possible. If it's not reasonable to have my suggested option, that's fine, we'll work around it.

**Comment by oehme** [comment]
@kcclaas Thank you for elaborating on the case. I'd say that a single multi-project build best models your current situation. You can then split it up into separately published projects later on, as the boundaries between projects get more stable.

**Comment by nniesen** [comment]
> What's the use case for this? Depending on the use case you are probably much better off with either[...]

Our projects are organized like an open source model where each project is a library that is then consumed by one **or more** other projects.

> 1. making all projects part of one multi-project build or

This is a monolithic project structure where the sub-projects aren't really re-used outside the single monolithic project.

> 2. using binary dependencies and using composite builds when you actually do need to co-develop them

This is cumbersome for cross-project refactoring and then testing the changes before pushing to CI.

But I get that you won't be changing the Gradle version of composite build it which is why we have our own [composite build](https://discuss.gradle.org/t/composite-build-workflow/20287/11).

**Comment by Kameecoding** [comment]
This bug is kind of obsolete, since 3.0 you can't even import projects where a composite build is included multiple times.

**Comment by ams-tschoening** [comment]
I have exactly the same use case like [mentioned before](https://github.com/eclipse/buildship/issues/360#issuecomment-320007146). The benefit of using composite builds is that those are pretty compatible with Eclipse workspaces and placing projects underneath, while at the same time each build could itself be a multi-project build. I'm considering that approach e.g. for implementing different versions of web services within one and the same build, making each version an individual project in a multi-project setup which then gets consumed as part of some composite.

**Comment by donat** [comment]
The latest version of Buildship is capable of importing multi-composites. I think that covers this issue as well. I'm closing this issue now. Let me know if there's still a use-case we need to tackle.
