### ISSUE TITLE
Tasks from closed projects should not be shown

### ISSUE THREAD

**Issue by oehme** [eclipse/buildship#433]
Task from closed projects are shown in the task view, but clicking on them leads to an NPE. They should be hidden and deactivated instead.

**Comment by donat** [comment]
The exception comes from `DefaultProjectConfigurationPersistence` which requires the projects to be open.  But that's not entirely true because we can load the configuration from the closed projects by directly reading the preferences file. Moreover, the preferences are updated even for closed projects upon update. I suggest we fix the problem by removing the requirement for the open projects.
