### ISSUE TITLE
JUnit view doesn't show results

### ISSUE THREAD

**Issue by matthew-groth** [eclipse/buildship#470]
Hi, I'm trying Eclipse for the first time (so I might be missing something) but used to work on my project with the NetBeans-Gradle plugin. In NetBeans, running the `gradle test ` task would show results in the test results window. I can see that Eclipse also has a `JUnit view`, but running tests does not show the results there.  I am running the tests by double clicking `test` under `verification` in the `Gradle Tasks` view, and results only show up in the console.

**Comment by oehme** [comment]
The JUnit view was unfortunately not extensible enough, so Buildship displays the tests in the Gradle `Execution view` instead.

**Comment by ddekany** [comment]
Do you mean "We know it's not very usable yet, but we know this is a problem and are working on a better view for showing test results"? It would be a more reassuring answer, than basically saying "use the Gradle Execution view".

I mean, how's one supposed to use the Gradle Execution view for this? You will see that the root node is red, and then start digging (means, scroll a lot) to find where's there deepest read child node. Because it's not even filterable to only show the red nodes. And when you find the deepest red node, it hows nothing about which test has failed and with what message. I have discovered that with right-clicking I can open the "Show failures..." window, but the stack trace is shows doesn't contain the actual assertion exception. There's a "Test summary" link in that window, but clicking it has simply no effect (for me).

So the best I can do is looking at the Console output (which is by default put into the background by the "Gradle Executions" tab, which honestly I don't think is an useful view in everyday work... all you see really is the top of the execution tree and time spinning). The console errors positions aren't clickable either, and by default they don't show a full stack trace.

Add to this that in Eclipse you have to have a separate Run Configuration for each project to run the JUnit tests, so to run tests of all project, certainly you want to use your build tool. Plus Eclipse ruins the classpath, as it can't comprehend that tests has its own dependencies. Not your mistake, but just makes people want to run tests with Gradle more.

**Comment by oehme** [comment]
We are not working on a better view in the near future, though a contribution would of course be warmly welcome.

**Comment by donat** [comment]
@ddekany FYI we added a few improvements to the executions view in the 2.1 release:
- By default, the tree is only expanded to the level of the executed tasks.
- If any build operation fails (e.g. a test) The execution view is expanded to show it. 

Also,  there is a somewhat hidden feature, which might be helpful for you. If you double click on a test in the executions view, it will navigate you to the corresponding test.

If the "Test summary" functionality is broken, then it's probably a regression. I'll look into that later.
