### ISSUE TITLE
Support import of project with nested projects

### ISSUE THREAD

**Issue by apupier** [eclipse/buildship#566]
- try to import Groovy project https://github.com/apache/groovy
- this error dialog will popup:
![image](https://user-images.githubusercontent.com/1105127/30316361-4887fd14-97a7-11e7-8638-e4191e9d1c61.png)

**Comment by oehme** [comment]
You defined both `src/main` and `src/main/antlr` as a source folder, which Eclipse does not allow. If this is truly what you want, then you should exclude "antlr" from `src/main`. Or you can change the source folder for the antlr plugin to something else like `src/antlr`. 

Consider putting your Java/Groovy source code under the conventional`src/main/java`/`src/main/groovy` instead. Then you won't need excludes.

**Comment by apupier** [comment]
I defined nothing, i just tried to import the project :(

**Comment by oehme** [comment]
Sorry, I assumed you were one of the project maintainers. I guess the Groovy team doesn't use Eclipse and thus didn't notice that its configuration is broken.

**Comment by apupier** [comment]
BuildShip has defined src/main and src/main/antlr itself as source folder as far as i know because they don't provide .classpath by default, so it would be nice if it can also configure the "exclude" itself.

groovy is providing otherwise a task to generate eclipse metadata but it is not working either. i think that it is cleaner to get rid of this eclipse metadata gradle task and that buildship can handle automatically this use case (with nested source folder)

**Comment by oehme** [comment]
Adding an exclude in Eclipse would just hide the fact that the project is configured wrongly. Its source layout is missing excludes. As a result, resources are being packaged when they shouldn't. I'm pretty sure this is not what the Groovy team intended, they probably just never noticed it, because those resources are not critical.

I don't think Buildship should be hiding this kind of problem. Instead, the project's `sourceSet` definitions should be fixed.

**Comment by apupier** [comment]
@oehme thanks for the explanation, i reported an issue to Groovy project then: https://issues.apache.org/jira/browse/GROOVY-8316
