### ISSUE TITLE
Buildship does not seem to care about Working Directory

### ISSUE THREAD

**Issue by Klaboe** [eclipse/buildship#584]
Builship-version: 2.1.2.v20170807-1321
Eclipse-version: 4.7.0 Oxygen
OS: Windows 10

My build.gradle applies a another gradle file that wants to create a file:

`def resFile = new File("build/test-results/test-results.json")`

Since the build-configuration looks like so:

<img width="331" alt="eclipse-buildship" src="https://user-images.githubusercontent.com/126390/30863275-e7862d44-a2d0-11e7-96ba-c67438e30987.PNG">

I would have assumed that the above code would place the file test-results.json in `path-to-my-workspace`/refund/build/test-results/

This does not seem to be the case, and I get a 

> build\test-results\test-results.json (The system cannot find the path specified)

This seems to be because it cant find its respective parent-folders, and if i do a 

`resFile.getParentFile().mkdirs();`

And then get the absolute-path, it is created in my Eclipse folder, not my workspace folder.

**Comment by donat** [comment]
`new File()` picks up the working directory of the jvm process. You should use [`project.file`](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:file(java.lang.Object)) in your build script which always creates project-relative paths. In your build script, you can directly call the `file()` method because it is delegated to the current project instance:

    def resFile = file("build/test-results/test-results.json")

**Comment by chrislong** [comment]
@donat I understand your workaround, but it still seems to me that Buildship is ignoring the Working Directory as set in the build configuration, or at least Buildship is treating it differently than other Eclipse launch types, such a Java application. What does the "Working Directory" setting mean/do in a Buildship launch?
