### ISSUE TITLE
Refresh Gradle Project action is not triggering eclipse.jdt.whenMerged

### ISSUE THREAD

**Issue by eric-milles** [eclipse/buildship#727]
Consider the following:
```groovy
plugins {
  id 'groovy'
  id 'eclipse'
}

eclipse {
  classpath.file.whenMerged {
    println '.classpath merged'
  }
  project.file.whenMerged {
    println '.project merged'
  }
  jdt.file.whenMerged {
    println '.settings/org.eclipse.jdt.core.prefs merged'
  }
}
```

When I trigger Refresh Gradle Project (or auto sync is enabled and `build.gradle` is saved), I only see the following in the Console view:
```
CONFIGURE SUCCESSFUL in 0s
.classpath merged
.project merged
```

Any customizations added within `jdt` like `file.whenMerged` or `file.withProperties` are not executed.

**Comment by donat** [comment]
I don't think we'll do that. We added support for `eclipse.classpath.file.whenMerged` to quickly enable Eclipse/JDT metadata customization where no Gradle API is available at the moment. This is more of a hack and we don't plan to do the same at other places. 

We plan to implement https://github.com/eclipse/buildship/issues/265 which will be a general solution for project customization.

**Comment by eric-milles** [comment]
Is there any way to at least give the user a clue `jdt.file.whenMerged` will not run?  I spent a lot of time reading the eclipse plugin docs to understand if I was doing something wrong.  When all along it was because Buildship was running 2 of 3 closures.

**Comment by BonusLord** [comment]
This threw me for a loop as well. The docs suggest that `jdt.file.whenMerged` or `jdt.file.withProperties` can be used to customize the JDT settings, but the stuff in those blocks never seems to run.

I see that https://github.com/eclipse/buildship/issues/265 is now closed; how would one about using that feature to apply custom JDT settings updates at project sync time?

Side note: I'm specifically looking to customize the `org.eclipse.jdt.core.compiler.release` property, which controls whether or not the `--release` flag is used for cross-compilation. Ideally, buildship would just be able to set this automatically based on the settings in the Java plugin since it is a pretty common / important setting.

**Comment by BonusLord** [comment]
Played around with this a little more, but couldn't really find a reliable way to make it work. I think I have a better understanding of what's going on now though.

So basically my primary goal is to control the value of the `org.eclipse.jdt.core.compiler.release` JDT flag on a per-project basis using Gradle + Buildship. However, unlike the `.classpath` and `.project` files, buildship does not appear to have support for making "arbitrary" customizations to the `org.eclipse.jdt.core.prefs` file where that property lives (instead you are limited to just the 3 properties that are formally defined on the `jdt` object in the Gradle eclipse plugin).

Here's what I tried as a workaround:
 - Defined a `withProperties` block which set the desired flag
 - Since buildship ignores the `withProperties` closure, I added the `eclipseJdt` task to `eclipse.synchronizationTasks` to force full-on regeneration of the `org.eclipse.jdt.core.compiler.release` file in the classic Eclipse plugin fashion

This workaround kind of works, but is flaky enough in practice that I wouldn't actually want to deploy it. The following problems occur:
 - The ordering of the properties in `org.eclipse.jdt.core.prefs` get scrambled (looks like HashMap iteration order) and a date header gets prepended to the file. This is mostly an aesthetic annoyance, but it can cause merge headaches too. (Normally, the updates that buildship makes to this file are done in a neat and orderly fashion that preserves the default property ordering.)
 - I haven't been able to figure out why, but Eclipse refuses to recognize that the `org.eclipse.jdt.core.compiler.release` property has changed after the `eclipseJdt` task re-writes the file. Tried: Refreshing, cleaning, closing+re-opening the project, but Eclipse was still acting like "--release" was disabled after `eclipseJdt` updated the file to enable it. The only things that seem to make it pick up the change are restarting the entire IDE or making a white-space only modification to the `org.eclipse.jdt.core.prefs` file manually (why does it work when I manually edit it, but not when the gradle task edits it...?)

So anyway, I guess I'm asking you to reconsider first-class support for arbitrary JDT settings customization, either via the `withProperties` closure or through some other mechanism. There's a ton of stuff in that file that would be super nice to be able to control using Gradle + Buildship, and waiting on dedicated APIs to be created for every property seems onerous. Additionally, using `synchronizationTasks` does not really seem to be a suitable workaround due to the issues I described.
