### ISSUE TITLE
Doesn't work with plugin com.android.application

### ISSUE THREAD

**Issue by bmaehr** [eclipse/buildship#779]
When using 
```
apply plugin: 'com.android.application'
```
eclipse is not able to include dependencies or build the source code.

The app project was not set up as gradle project by the gradle project import. After fixing this manually still the buildpath is not correctly set up.
If using plugin 'com.android.application' instead of 'java-library' the build path of the eclipse project looses all dependencies.

buildTypes and productFlavors are not supported.

**Comment by mortalis13** [comment]
Use this Gradle plugin: https://github.com/greensopinion/gradle-android-eclipse
to generate Eclipse project classpath.
It will help to resolve compile errors and auto imports.

Then you just import your project as Eclipse project, create new Run configuration as Gradle Project with your task (`assembleDebug`) and it builds android project without ADT, only with Gradle.

**Comment by donat** [comment]
It might make sense to take another look.

**Comment by CsCherrYY** [comment]
we can simply to reproduce this via Android Studio `new project -> Basic Activity -> Language: Java` and finish the wizard.

**Comment by donat** [comment]
I managed to add classpath entries by manually defining `plusConfigurations`:
```
afterEvaluate {
  eclipse {
    classpath {
      plusConfigurations = [configurations.debugUnitTestRuntimeClasspath]
    }
  }
}
```

**Comment by nisargjhaveri** [comment]
The gradle plugin @mortalis13 mentioned seems to be unmaintained and archived. Also, if would be great if android support works without any changes in build.gradle, so that people can easily use this in other editors like eclipse and vscode without having to change something in a shared app.

Looking forward to a solution for this! Happy to help if I can, though I'm not very familiar with any of these.

**Comment by nisargjhaveri** [comment]
@donat, I'm trying to see how stuff works. I tried adding this to my app/build.gradle and sync in vs code. Doesn't seem to help, the java files still errors that it is not on the classpath of the project. What am I missing?

```
apply plugin: 'eclipse'

afterEvaluate {
  eclipse {
    classpath {
      plusConfigurations = [configurations.debugUnitTestRuntimeClasspath]
    }
  }
}
```

**Comment by CsCherrYY** [comment]
@nisargjhaveri I think the snippet above will help resolve classpath for you. Besides, there are serveal things to do to make android project work:

1. add source set. Since android plugin will not adopt java plugin's structure hypothesis, you might have to add main source set manually, e.g., 
```
allprojects {
     plugins.withId('com.android.application', { _ ->
             sourceSets {
                 main {
                     java {
                         srcDir 'src/main/java'
                     }
                 }
             }
     })
 }
```
2. it seems that you have to manully add `android.jar` in the project platfrom to your classpath.

Then it might work. Anyway, it would be great if we can have a built-in support in buildship so we can import andorid project successfully at least.
