### ISSUE TITLE
Eclipse and the command line handle src/main/resources differently

### ISSUE THREAD

**Issue by wilkinsona** [eclipse/buildship#812]
When Buildship is used to import a Java project into Eclipse, everything in `src/main/resources` is treated in much the same way as if it was in `src/main/java`. This is problematic as it can lead to differences in behaviour between Eclipse and the command line. 

[Here](https://github.com/eclipse/buildship/files/2625758/buildship-resources-bug.zip) is a small sample project that illustrates the differences we've encountered in our real-world project (a prototype for a new version of [Spring Initializr](https://github.com/spring-io/initializr)) while trying to migrate the build from Maven to Gradle. The differences are:

- The project is marked with a compilation error due to `Sample.java` not being in the right package
- The project's one test fails as `sample/Sample.java` can't be found on the classpath

When built with Maven and using m2e in Eclipse, we do not see the problem. m2e excludes `**` from the `classpathentry` and I believe it then has its own builder to copy the resources into the configured `output` location.

**Comment by donat** [comment]
This is currently the expected behavior: Buildship models the Gradle resources in Eclipse with source folders. For the most part it works just fine, but in your case it's problematic because you have `.java` files in your resources folder and JDT tries to compile them. 

It might make sense to implement it the M2E way, but given our schedule and staffing I don't see it happening soon. Contributions are welcome though. 😉

Luckily there's an easy fix to your configuration. You can convert the resources dir into a library dependency with the snippet below. With that in place the resources are still available on the classpath, but JDT won't try to compile them.
```

import org.gradle.plugins.ide.eclipse.model.Library

apply plugin: 'java'
apply plugin: 'eclipse'

eclipse {
    classpath {
        file {
            whenMerged {
                entries.removeAll { it.path == 'src/main/resources' }
                entries += new Library(fileReference(file('src/main/resources')))
            }
        }
    }
}
```
