### ISSUE TITLE
Java Library transitive dependencies in eclipse

### ISSUE THREAD

**Issue by regrog** [eclipse/buildship#815]
I asked this in Gradle forum but maybe this is the right place: https://discuss.gradle.org/t/java-library-transitive-dependencies-in-eclipse/29679

In my multiproject build I declare my projects dependencies using api or implementation.
In eclipse everything seems to work fine but running a build using gradle, because of implementation usage, transitive dependencies are (correctly) prevented.

In eclipse implementation is not used in the same way I think.
Both api or implementation are added as Project and External Dependencies.

Here the example: [projectA.zip](https://github.com/eclipse/buildship/files/2644138/projectA.zip)

`api3` depends on `api2` that depends on `api1`.
the dependency is declared using **implementation** but `api3` in **Project and External Dependencies** also depends on `api1`, and this should be an error.

![image](https://user-images.githubusercontent.com/7606880/49445278-db0ba880-f7d1-11e8-8434-5dd4a44e9cd0.png)

versions:
gradle 4.10.2
buildship 3
eclipse 2018-09 (4.9.0)

Thanks

**Comment by donat** [comment]
I'm afraid that's not possible now. Buildship does not provide separation between the dependency configurations as Eclipse is limited to one compile classpath per project. Instead, a union of resolved configurations is assigned to each project.

**Comment by oehme** [comment]
To elaborate a bit more on the above: Buildship needs to use the project's runtime classpath, as otherwise running your application from Eclipse would no longer work. The runtime classpath contains all the dependencies, not just API ones.

**Comment by sorennielsen** [comment]
I know this issue is closed but just want to add that I am also struggling with this.
Not having dependencies correctly enforced in your IDE means that you don't get proper feedback until the CI server tries to build the code.
Maven is able to do this so it seems that this is not an issue with Eclipse.

The idea with having proper dependencies set up is to limit the amount of "wrong" content assist.

**Comment by loetifuss** [comment]
Same problem for me. We have a large multi-module build with a framework layer that has an abstraction layer hiding a lot of external libraries behind it's API. This framework layer is used in all the downstream projects. With all dependencies (api and implementation) on the Eclipse classpath that abstraction would be useless since everyone would be able to see and use the external libs when coding in Eclipse.

**Comment by jjohannes** [comment]
You can get this working in Eclipse by configuring the Eclipse/Gradle sync to use the compile classpath. But it might break functionality related to running from Eclipse, as explained this the [comment above](https://github.com/eclipse/buildship/issues/815#issuecomment-447889870).

You can do something like this in `build.gradle` of the root project:

```
subprojects {
  plugins.withType(EclipsePlugin) { // Plugin added by Buildship on project sync
    plugins.withType(JavaPlugin) {  // Modify the defaults only after a Java plugin was applied
      eclipse {
        configurations {
          // === workaround for (TODO link issue/PR)
          apiElements {
            attributes {
              attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
            }
          }
          runtimeElements {
            attributes {
              attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, "UNUSED"))
            }
          }
          // ===
          compileClasspath {
            attributes {
              attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
            }
          }
        }
        classpath {
          plusConfigurations = [configurations.compileClasspath] // maybe also add configurations.testCompileClasspath
        }
      }
    }
  }
}
```
