### ISSUE TITLE
gradle import of graphql-java won't add the generated-src folder

### ISSUE THREAD

**Issue by etienne-sf** [eclipse/buildship#853]
Hello,

  I'm trying to compile the graphql-java project.

It's available here: https://github.com/graphql-java/graphql-java.git

The issue I encounter is that the generateGrammarSource gradle command generates a "/generated-src/antlr/main/graphql/parser/antlr".
But this folder is not added to the eclipse buildpath.

Adding it manually makes the trick.

I would expect gradle to automatically add this source folder to the eclipse project.
(like m2e eclipse maven plugin does)

Etienne

**Comment by eric-milles** [comment]
I don't think this is a buildship issue.  The project does nothing to inform buildship of any eclipse-specific steps.  As the project is, buildship can't see the antlr steps. That's not to say you can make edits to build.gradle so that it can inform eclipse/buildship on how to 1) generate the parser sources from the grammar(s) and 2) add the generated source location as a source folder (or generate into `src/main/antlr`).

I suggested in https://github.com/groovy/groovy-eclipse/issues/800 that the build.gradle could be updated with eclipse steps and submitted as a PR to graphql-java.  I can help with this if OP does not have Gradle/Eclipse experience.

**Comment by etienne-sf** [comment]
Yes, I've read your suggestion.

But: 
- I don't know gradle (and I don't want to invest in it for the moment)
- As the project properly builds when starting from the command line, I guess enough information exists in the project for the use of the generated classes
- **There is a workaround, once one has found the compilation issue: manually add the source folder for the generated code**.

I raised this issue as I think it should work out of the box. And I have no clue about how difficult it could be to make it work.
As I can't help to solve it, the best way could be to close it as "won't fix" (don't know if it's possible here), if relevant.

Etienne

**Comment by eric-milles** [comment]
Gradle by its nature as a build script DSL can be used to specify infinitely complex build steps/tasks.  Buildship/Eclipse cannot possibly interpret all possibilities.  In the case of `graphql-java`, extra steps are added for antlr to generate extra sources and then these are compiled as part of the java compilation task(s).  There is nothing in the build script that lets eclipse know about the extra source location.  There is Gradle DSL (using the `eclipse` plug-in) to inform Buildship of the additional source folder.  And also to add a builder for the antlr source generation.

As I said here and in groovy-eclipse, I'm willing to help develop the extra Gradle DSL necessary to get the project importing into eclipse seamlessly.  What I would need from you is to test the changes and in the end, submit a Pull Request to `graphql-java`.

**Comment by oehme** [comment]
Closing since this since the fault is in the build script of graphql-java. It should add `build/generated-source` to `sourceSets.main.java`, not adding it directly on the JavaCompile task.
