### ISSUE TITLE
classes from generated sources sets are not included in java run configuration

### ISSUE THREAD

**Issue by JWood48** [eclipse/buildship#861]
A gradle project with a **generated** source set will compile in eclipse, but when trying to run the application from eclipse the generated classes are not visible to the application.

Example project here: https://github.com/JWood48/eclipse-run-config-error

In the generated .classpath file it seems like the **generated** source set has an attribute: **gradle_used_by_scope = "generated"**

if changed to **gradle_used_by_scope = "generated,main"** it works - see workaround in example repository

Generated (and other) sourcesets should always be visible to the run configurations!

**Comment by donat** [comment]
This is the expected behavior. In your example, the `generated` source set is independent of `main`, therefore Buildship filters it if you launch an application from the `main` source set. Your workaround is correct though, that's how you influence the runtime classpath filtering. 

FYI we plan to ditch the whole runtime classpath filtering functionality. Our implementation, although general, is hard to understand and we can exchange it with Eclipse's test sources functionality.
