### ISSUE TITLE
JUnit 5 test cannot be launched from Gradle Spring Boot 2.2.5 project

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/buildship#980]
This is related to https://github.com/spring-projects/sts4/issues/431

Maven project with the same JUnit 5.5.2 on the classpath runs tests fine in Eclipse 4.15 + M2E + Buildship Gradle 3.x or STS 4.6.0 (i.e. Right-click the project Run As... -> JUnit Test)

While the equivalent Gradle project with JUnit 5.5.2 on the classpath fails when tests are launched (Right-click the project Run As... -> JUnit Test)

Seems like something is off in the project test launch with the Gradle project... While it works fine with M2E...

Projects are attached below

[demo-plain-gradle.zip](https://github.com/eclipse/buildship/files/4395507/demo-plain-gradle.zip)
[demo-plain-maven.zip](https://github.com/eclipse/buildship/files/4395508/demo-plain-maven.zip)

**Comment by brychcy** [comment]
Related changes for maven can be found in https://bugs.eclipse.org/bugs/show_bug.cgi?id=551298

**Comment by donat** [comment]
The attached example has a missing dependency. I was able to run the junit5 test after adding the following dependency:

    testImplementation 'org.junit.platform:junit-platform-engine:+'

**Comment by christophs78** [comment]
@donat : I don´t think this is due to missing dependency. It´s due the some version mismatch. Please have a look at https://github.com/spring-projects/sts4/issues/431.
I had this issue in an real world project. Exact same projects works with Ecipse 4.14 and fails with Eclipse 4.15.
When i import demo-plain-gradle.zip into eclipse 4.15 junit-platform-engine is there. "Only" a version not compatible with Eclipse 4.15 and the included Buildship-Plugin.
![image](https://user-images.githubusercontent.com/10461942/79736626-65d34180-82fa-11ea-81bd-2024aa434d0e.png)

**Comment by tryptophane** [comment]
Can this bug please be reopened?

**Comment by jdneo** [comment]
hello guys! Is there any plan to fix this issue?

**Comment by coryroloff** [comment]
This is causing issues for my project as well. Would be great to get a fix. :)

**Comment by donat** [comment]
Hi! I'll look into it next week.

**Comment by j-krose** [comment]
+1 on seeing this issue.  Thanks @donat.

**Comment by donat** [comment]
@christophs78 One thing to clarify here is that Buildship doesn't introduce or modify Gradle dependencies. Whatever ends up in a classpath comes from the dependency declarations in the build scripts.

**Comment by donat** [comment]
I've looked into how m2e handles this case. Basically it adds the missing dependencies to the classpath. I think Buildship should do something similar: it should automatically inject the `org.junit.platform:junit-platform-launcher` dependency (with the same version as `junit-platform-engine`) to the classpath.

Consequently, it is a viable workaround to add the `org.junit.platform:junit-platform-launcher` dependency to the build script.

**Comment by christophs78** [comment]
@donat: That´s some kind of weird. I took demo-plain-gradle.zip provided at the top of this issue. It work´s with fresh Eclipse 2019-12. And it does not work with fresh Eclipse 2020-03. (and fresh workspace, ...)
Has there been some other change with Eclipse 2020-03 which may be part of this issue?

**Comment by donat** [comment]
Buildship didn't change but Eclipse JDT did:

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/419883/82820809-28d30f80-9ea3-11ea-8d5a-d0d677af66ef.png">

Maybe it's a bug in the JUnit tooling.

**Comment by christophs78** [comment]
Yep. :-)

Eclipse 4.14 (2019-12) comes with JUnit 5.5.1
Eclipse 4.15 (2020-03) comes with JUnit 5.6.0

Does m2e add the missing dependency since "ever" or is this something that was added over time?

IMO m2e is a good reference. Is there some additional "magic" / logic in m2e or does it add the `org.junit.platform:junit-platform-launcher` "always"?

**Comment by donat** [comment]
Just checked: updating the JUnit platform dependencies to 1.6.0 fixes the test execution in Eclipse.

**Comment by christophs78** [comment]
Do you have a Github-Link to the code-fragment where m2e add this dependency (`org.junit.platform:junit-platform-launcher`) automatically?

**Comment by donat** [comment]
Sure: https://github.com/eclipse/m2e-core/blob/master/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/launch/MavenRuntimeClasspathProvider.java#L264-L279

**Comment by brychcy** [comment]
Some background: jdt.ui adds its bundled "org.junit.platform.launcher" if it doesn't find it on the runtime classpath (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=526502).

But it only has a specific version bundled (and has no mechanism to download other version).
Only if that one is compatible with what you have on the classpath, everything works.

Unfortunately, it looks like JUnit5 doesn't really try to achieve compatiblity in presence of version conflicts between its various artifacts.

So for m2e (which can download other versions), **matching** versions of launcher and engines are added  (as seen in the gerrit in above linked https://bugs.eclipse.org/bugs/show_bug.cgi?id=551298)

BTW: Originally I it had tried to dynamically find out which dependencies are added by the maven-surefire plugin, but there is no AI to query the runtime classpath computed by it, so direct derivation from the versions found in the dependencies was done instead.

**Comment by christophs78** [comment]
https://github.com/eclipse/m2e-core/commit/7767192faacda387c578e1d6c74bcd1bec81f2c9#diff-31a14d836cb3943d5c9ebeca692a5569 - This was your commit to fix this for m2e?

**Comment by brychcy** [comment]
yes

**Comment by donat** [comment]
I have a local prototype of how it can be done in Buildship. I'll try to allocate time for the proper implementation in the upcoming days.

**Comment by donat** [comment]
There's also another workaround: delegate the test execution to Gradle.

**Comment by donat** [comment]
I've created a draft implementation to fix the issue: https://github.com/eclipse/buildship/pull/1001. Once I get a successful CI to build I'll then create a snapshot release that you can use for evaluation.

**Comment by lukeu** [comment]
So in practical terms, is this understanding correct...?

 * to update Eclipse to 4.15 or 4.16 without this fix, the Gradle-based project must be updated to use JUnit 5.6.x
 * if we need to build old versions of our project, we can at least run its tests via the Gradle CL
 * after this fix, Eclipse will be able to execute any JUnit 5 version again?

**Comment by donat** [comment]
@lukeu right now, you can work around the problem by explicitly adding the `junit-platform-engine` to the classpath:

    testImplementation 'org.junit.platform:junit-platform-engine:+'

With the fix in place, this will happen automatically. I'm doing a more thorough investigation of why it doesn't work already. IMHO Gradle should support this automatically and we should not resort to build magic I did in #1001.

**Comment by donat** [comment]
I'd like to also mention that you can always use the __Delegate to Gradle__ feature where this problem is non-existent.

**Comment by lukeu** [comment]
Hi @donat, 
> @lukeu right now, you can work around the problem by explicitly adding the `junit-platform-engine` to the classpath:
> ```
> testImplementation 'org.junit.platform:junit-platform-engine:+'
> ```

Thanks for the tip. I played around with that, setting it centrally (in a multi-project build) both alongside and instead of:

                "org.junit.jupiter:junit-jupiter-api:$junit5Version",
                "org.junit.jupiter:junit-jupiter-params:$junit5Version",

and noticed that it (for example) caused Gradle to download something from JUnit 5.7.0-M1. However I had trouble getting it to complete our (complex) synchronization. It failed in a step that needs to compile a test extension based on `InvocationInterceptor` (just like the example from the [JUnit5 docs](https://junit.org/junit5/docs/current/user-guide/#extensions-intercepting-invocations) ).  This was encountered in both Eclipse 2019-06 and 2020-06. Maybe I got something wrong.

Meanwhile, just bumping the `junit5Version` to 5.6.2 seemed to make both Eclipse 2019-06 (to my surprise) and 2020-06 happy. So "touch wood" that is a sufficient workaround for other Eclipse versions in between, too.

**Comment by donat** [comment]
In my example project, it was enough to use the latest version of `junit-platform-engine`.  The correct approach is to specify the same version for all `org.junit.jupiter` dependencies.

**Comment by donat** [comment]
We still have a discussion internally on how to solve this issue. Until that, explicitly adding `junit-platform-engine` to the dependencies is a good workaround.

**Comment by jjohannes** [comment]
I clarified some things about JUnit5 and how it works in Gradle:

- In JUnit5, things are backward compatible. That's why it works, also with older versions of Gradle or Eclipse, if you use a version of JUnit5 in your project that corresponds to the one packaged or is newer.
- In Gradle, we package a version of `junit-platform-engine` that corresponds to the package versions of `junit-platform-launcher`. And then there is some classloader isolation in the test workers, such that this version is hidden during test run (and the version matching the dependencies in the build file is used instead). This is why the given example works with Gradle and does not cause the `NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener` error. 

I think for now, the solution here is:
- If possible, update the JUnit5 versions in your build.
- Otherwise, add `testRuntimeOnly 'org.junit.platform:junit-platform-launcher'` as dependency (which will cause Eclipse to use the older version of the launcher that matches the versions in your build).

An improvement on the Gradle side would be to have Gradle automatically download the launcher that corresponds to the version used in the build. (Which is basically the functionality @donat drafted but moved further into the core of Gradle's JUnit5 support.)

**Comment by donat** [comment]
Future work moved to the gradle/gradle issue tracker: https://github.com/gradle/gradle/issues/13955
