### ISSUE TITLE
Add comment shortcut in .gradle files editor

### ISSUE THREAD

**Issue by leaqui** [eclipse/buildship#989]
Add comment shortcut (E.g. ctrl + shift + C) in .gradle files editor.

Please let me know if it needs more specification.

**Comment by donat** [comment]
This would make a good candidate for a pull request.

**Comment by Abhiuday-Surya** [comment]
can you specify a little more what is to be done here?

**Comment by leaqui** [comment]
It's working fine at 3.1.9.v20240115-1636 version, so I close the issue. Thanks!

**Comment by oleosterhagen** [comment]
The support for comments in the editor comes from the **TextMate Language Pack** of [Eclipse TM4E](https://github.com/eclipse/tm4e).

This plugin is included since Eclipse 2024-06 via _Eclipse Wild Web Developer_ (https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/commit/ff48fba15f8f97cddfaca5c0da0fd194373d7380).

In older versions of Eclipse it can be installed manually:

1. _Help > Install New Software..._
2. Select an update site (e.g. https://download.eclipse.org/releases/2024-03)
3. Install: _Programming Languages > TextMate Language Pack_
