### ISSUE TITLE
cannot depend on testFixtures in implementation source set

### ISSUE THREAD

**Issue by rdehuyss** [eclipse/buildship#991]
I have a dedicated test project where the source set "src/main/java" contains references to classes located in testFixtures.

These imports cannot be resolved.

```
plugins {
    id 'java-library'
}

dependencies {
    implementation project(':core')
    implementation testFixtures(project(":core"))
    
    testImplementation project(':core')
    testImplementation testFixtures(project(":core"))
}
```
### Expected Behavior
The imports to classes in testFixtures can be resolved in the source set "src/main/java".

### Current Behavior
The imports to classes in testFixtures can NOT be resolved in the source set "src/main/java".

### Context
- Cannot use Eclipse because of it
- gradle command line works
- Intellij works

### Steps to Reproduce 
See attached example project
[eclipse-gradle-bug.zip](https://github.com/eclipse/buildship/files/4569313/eclipse-gradle-bug.zip)

### Your Environment
- Eclipse Version: 2020-03 (4.15.0), Build id: 20200313-1211
- Eclipse Buildship	3.1.4.v20200326-1718	org.eclipse.buildship

**Comment by donat** [comment]
The pasted example project doesn't work from the command line:
```
[~/Downloads/eclipse-gradle-bug]$ ./gradlew compileJava

> Task :tests:compileJava FAILED
/Users/donat/Downloads/eclipse-gradle-bug/tests/src/main/java/another/name/SomeClass.java:5: error: cannot find symbol
        public SomeClass(SomeTestFixture someTestFixture) {
                         ^
  symbol:   class SomeTestFixture
  location: class SomeClass
1 error
```

This is because the classes from the test fixtures are not available in the main source set of a downstream project dependency.


At the same time, the report is valid. `tests/src/test/java/another/name/AnotherClass.java` should be able to depend on `core/src/testFixtures/java/some/name/SomeTestFixture.java` via test fixtures.

This has been fixed in Gradle 6.8: https://github.com/gradle/gradle/issues/14932. If you are stuck with a pevious Gradle version then check the workaround in the issue.
